version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db1:/var/lib/mysql
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'jose-emi'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - "3306:3306"

# Names our volume
volumes:
  db1: 