version: "3.3"
services:
  api:
    build: ./library-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: node ./app.js
    environment:
      WAIT_HOSTS: db:3306

  frontend:
    build: ./library-frontend
    ports:
      - "8081:8080"
    command: npm run serve

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "library"
      MYSQL_USER: "lab4"
      MYSQL_PASSWORD: "laboratorio4"
      MYSQL_ROOT_PASSWORD: "laboratorio4"

volumes:
  db:
